from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .waves import EPS0, MU0, Wave


@dataclass(frozen=True)
class NonlinearSource:
    """Nonlinear polarization source wave at 2 omega."""

    label: str
    k: np.ndarray
    polarization: np.ndarray
    omega: float


@dataclass(frozen=True)
class SingleInterfaceSources:
    """The ee, oo, and eo inhomogeneous source polarizations."""

    ee: NonlinearSource
    oo: NonlinearSource
    eo: NonlinearSource


@dataclass(frozen=True)
class InhomogeneousField:
    """Particular 2 omega electric field generated by a nonlinear source."""

    label: str
    k: np.ndarray
    electric: np.ndarray
    polarization: np.ndarray
    omega: float
    residual: np.ndarray
    operator_condition: float
    ill_conditioned: bool
    solution_method: str


@dataclass(frozen=True)
class SingleInterfaceInhomogeneousFields:
    """The ee, oo, and eo inhomogeneous 2 omega fields."""

    ee: InhomogeneousField
    oo: InhomogeneousField
    eo: InhomogeneousField


@dataclass(frozen=True)
class MultilayerSources:
    """SHAARP.ml-style inhomogeneous source waves for one nonlinear layer."""

    f1f1: NonlinearSource
    f2f2: NonlinearSource
    f1f2: NonlinearSource
    b1b1: NonlinearSource
    b2b2: NonlinearSource
    b1b2: NonlinearSource
    f1b1: NonlinearSource
    f2b2: NonlinearSource
    f1b2: NonlinearSource
    f2b1: NonlinearSource

    def as_list(self) -> list[NonlinearSource]:
        return [
            self.f1f1,
            self.f2f2,
            self.f1f2,
            self.b1b1,
            self.b2b2,
            self.b1b2,
            self.f1b1,
            self.f2b2,
            self.f1b2,
            self.f2b1,
        ]


@dataclass(frozen=True)
class MultilayerInhomogeneousFields:
    """Particular fields for the ten SHAARP.ml layer source waves."""

    f1f1: InhomogeneousField
    f2f2: InhomogeneousField
    f1f2: InhomogeneousField
    b1b1: InhomogeneousField
    b2b2: InhomogeneousField
    b1b2: InhomogeneousField
    f1b1: InhomogeneousField
    f2b2: InhomogeneousField
    f1b2: InhomogeneousField
    f2b1: InhomogeneousField

    def as_list(self) -> list[InhomogeneousField]:
        return [
            self.f1f1,
            self.f2f2,
            self.f1f2,
            self.b1b1,
            self.b2b2,
            self.b1b2,
            self.f1b1,
            self.f2b2,
            self.f1b2,
            self.f2b1,
        ]


def compute_pnl_voigt(d_voigt_lab: np.ndarray, e1: np.ndarray, e2: np.ndarray, factor: complex = 1.0) -> np.ndarray:
    """Port Mathematica `computePNL`.

    Mathematica computes:

    factor * dL. {E1x E2x, E1y E2y, E1z E2z,
                   E1y E2z + E1z E2y,
                   E1x E2z + E1z E2x,
                   E1y E2x + E1x E2y}
    """

    d = np.asarray(d_voigt_lab, dtype=complex)
    if d.shape != (3, 6):
        raise ValueError("d_voigt_lab must be a 3x6 matrix.")
    a = np.asarray(e1, dtype=complex)
    b = np.asarray(e2, dtype=complex)
    if a.shape != (3,) or b.shape != (3,):
        raise ValueError("e1 and e2 must be length-3 vectors.")
    products = np.array(
        [
            a[0] * b[0],
            a[1] * b[1],
            a[2] * b[2],
            a[1] * b[2] + a[2] * b[1],
            a[0] * b[2] + a[2] * b[0],
            a[1] * b[0] + a[0] * b[1],
        ],
        dtype=complex,
    )
    return factor * (d @ products)


def pairwise_nonlinear_sources(
    d_voigt_lab: np.ndarray,
    waves: list[Wave],
    pairs: list[tuple[int, int, str]],
) -> dict[str, NonlinearSource]:
    """Unified SHAARP 2-omega nonlinear-source generator shared by the
    single-interface (SI) and multilayer (ML) paths.

    SHAARP.si and SHAARP.ml historically built their inhomogeneous sources with
    different symbols (SI: ``ee``/``oo``/``eo`` over the two fundamental modes;
    ML: ``f1f1``..``f2b1`` over the four forward/backward modes), but it is ONE
    operation: for each pair of fundamental waves ``(waves[i], waves[j])`` form a
    2-omega source with the SHAARP factor convention -- a SELF pair (``i == j``)
    uses factor 1 (so ``k = 2 k_i`` and ``omega = 2 omega_i``); a CROSS pair
    (``i != j``) uses factor 2 (``k = k_i + k_j``). This function is the single
    place that rule lives; SI and ML are just different ``(waves, pairs)`` inputs.
    """

    if not waves:
        raise ValueError("waves must be non-empty.")
    omega0 = waves[0].omega
    if not all(np.isclose(w.omega, omega0) for w in waves):
        raise ValueError("All fundamental waves must share the same omega.")
    sources: dict[str, NonlinearSource] = {}
    for i, j, label in pairs:
        factor = 1 if i == j else 2
        sources[label] = _source_from_pair(label, d_voigt_lab, waves[i], waves[j], factor=factor)
    return sources


# Canonical pair specs (index into the wave list) -- the only difference between
# the SI and ML nonlinear-source sets is which pairs are formed.
_SI_SOURCE_PAIRS = [(0, 0, "ee"), (1, 1, "oo"), (0, 1, "eo")]
# Labels are UPPERCASE to preserve the existing NonlinearSource.label strings.
_ML_SOURCE_PAIRS = [
    (0, 0, "F1F1"), (1, 1, "F2F2"), (0, 1, "F1F2"),
    (2, 2, "B1B1"), (3, 3, "B2B2"), (2, 3, "B1B2"),
    (0, 2, "F1B1"), (1, 3, "F2B2"), (0, 3, "F1B2"), (1, 2, "F2B1"),
]


def single_interface_sources(d_voigt_lab: np.ndarray, fast_wave: Wave, slow_wave: Wave) -> SingleInterfaceSources:
    """Generate SHAARP single-interface inhomogeneous sources: ee, oo, eo.

    The argument names are historical from the early fast/slow port. For
    physical SHAARP ordinary/extraordinary source labels, pass the
    extraordinary wave first and the ordinary wave second.

    Thin wrapper over the unified :func:`pairwise_nonlinear_sources` (the same
    primitive the multilayer path uses) with the SI pair set ee/oo/eo.
    """

    src = pairwise_nonlinear_sources(d_voigt_lab, [fast_wave, slow_wave], _SI_SOURCE_PAIRS)
    return SingleInterfaceSources(ee=src["ee"], oo=src["oo"], eo=src["eo"])


def multilayer_sources(
    d_voigt_lab: np.ndarray,
    forward_1: Wave,
    forward_2: Wave,
    backward_1: Wave,
    backward_2: Wave,
) -> MultilayerSources:
    """Generate the ten SHAARP.ml inhomogeneous source waves for one layer.

    Thin wrapper over the unified :func:`pairwise_nonlinear_sources` (the same
    primitive the single-interface path uses) with the ML forward/backward pair set.
    """

    waves = [forward_1, forward_2, backward_1, backward_2]
    src = pairwise_nonlinear_sources(d_voigt_lab, waves, _ML_SOURCE_PAIRS)
    return MultilayerSources(
        f1f1=src["F1F1"], f2f2=src["F2F2"], f1f2=src["F1F2"],
        b1b1=src["B1B1"], b2b2=src["B2B2"], b1b2=src["B1B2"],
        f1b1=src["F1B1"], f2b2=src["F2B2"], f1b2=src["F1B2"], f2b1=src["F2B1"],
    )


def cross_matrix(vector: np.ndarray) -> np.ndarray:
    """Return the matrix K such that K @ a == vector x a."""

    v = np.asarray(vector, dtype=complex)
    if v.shape != (3,):
        raise ValueError("vector must be a length-3 vector.")
    return np.array(
        [
            [0.0, -v[2], v[1]],
            [v[2], 0.0, -v[0]],
            [-v[1], v[0], 0.0],
        ],
        dtype=complex,
    )


def curl_curl_matrix(k: np.ndarray) -> np.ndarray:
    """Plane-wave matrix for Mathematica `Curl[Curl[E]]`.

    SHAARP uses fields proportional to exp(I (omega t - k.r)). With that
    convention, Curl[Curl[C exp(I(omega t-k.r))]] contributes
    -k x (k x C) times the same phase.
    """

    kx = cross_matrix(k)
    return -(kx @ kx)


def solve_inhomogeneous_field(
    epsilon_2omega_lab: np.ndarray,
    source: NonlinearSource,
    *,
    mu: float = MU0,
    eps0: float = EPS0,
    condition_threshold: float = 1e12,
    solution_policy: str = "solve",
) -> InhomogeneousField:
    """Solve the Mathematica `solveInhom` linear equation for one source.

    The solved equation is:

        Curl[Curl[E_inh]] = omega**2 * mu * eps0 * (epsilon @ E_inh + PNL)

    after extracting the coefficient of the source plane-wave phase.
    """

    epsilon = np.asarray(epsilon_2omega_lab, dtype=complex)
    if epsilon.shape != (3, 3):
        raise ValueError("epsilon_2omega_lab must be a 3x3 matrix.")
    k = np.asarray(source.k, dtype=complex)
    polarization = np.asarray(source.polarization, dtype=complex)
    if k.shape != (3,) or polarization.shape != (3,):
        raise ValueError("source k and polarization must be length-3 vectors.")

    alpha = (source.omega**2) * mu * eps0
    operator = curl_curl_matrix(k)
    system = operator - alpha * epsilon
    operator_condition = float(np.linalg.cond(system))
    ill_conditioned = bool((not np.isfinite(operator_condition)) or operator_condition >= condition_threshold)
    electric, solution_method, ill_conditioned = _solve_inhomogeneous_linear_system(
        system,
        alpha * polarization,
        ill_conditioned=ill_conditioned,
        condition_threshold=condition_threshold,
        solution_policy=solution_policy,
    )
    residual = operator @ electric - alpha * (epsilon @ electric + polarization)
    return InhomogeneousField(
        label=source.label,
        k=k,
        electric=electric,
        polarization=polarization,
        omega=source.omega,
        residual=residual,
        operator_condition=operator_condition,
        ill_conditioned=ill_conditioned,
        solution_method=solution_method,
    )


def solve_single_interface_inhomogeneous_fields(
    epsilon_2omega_lab: np.ndarray,
    sources: SingleInterfaceSources,
    *,
    mu: float = MU0,
    eps0: float = EPS0,
    condition_threshold: float = 1e12,
    solution_policy: str = "solve",
) -> SingleInterfaceInhomogeneousFields:
    """Solve `solveInhom`-style particular fields for ee, oo, and eo sources."""

    return SingleInterfaceInhomogeneousFields(
        ee=solve_inhomogeneous_field(
            epsilon_2omega_lab,
            sources.ee,
            mu=mu,
            eps0=eps0,
            condition_threshold=condition_threshold,
            solution_policy=solution_policy,
        ),
        oo=solve_inhomogeneous_field(
            epsilon_2omega_lab,
            sources.oo,
            mu=mu,
            eps0=eps0,
            condition_threshold=condition_threshold,
            solution_policy=solution_policy,
        ),
        eo=solve_inhomogeneous_field(
            epsilon_2omega_lab,
            sources.eo,
            mu=mu,
            eps0=eps0,
            condition_threshold=condition_threshold,
            solution_policy=solution_policy,
        ),
    )


def solve_multilayer_inhomogeneous_fields(
    epsilon_2omega_lab: np.ndarray,
    sources: MultilayerSources,
    *,
    mu: float = MU0,
    eps0: float = EPS0,
    condition_threshold: float = 1e12,
    solution_policy: str = "solve",
) -> MultilayerInhomogeneousFields:
    """Solve `solveInhom` fields for all ten SHAARP.ml layer sources."""

    kwargs = {
        "mu": mu,
        "eps0": eps0,
        "condition_threshold": condition_threshold,
        "solution_policy": solution_policy,
    }
    return MultilayerInhomogeneousFields(
        f1f1=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f1f1, **kwargs),
        f2f2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f2f2, **kwargs),
        f1f2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f1f2, **kwargs),
        b1b1=solve_inhomogeneous_field(epsilon_2omega_lab, sources.b1b1, **kwargs),
        b2b2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.b2b2, **kwargs),
        b1b2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.b1b2, **kwargs),
        f1b1=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f1b1, **kwargs),
        f2b2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f2b2, **kwargs),
        f1b2=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f1b2, **kwargs),
        f2b1=solve_inhomogeneous_field(epsilon_2omega_lab, sources.f2b1, **kwargs),
    )


def _source_from_pair(
    label: str,
    d_voigt_lab: np.ndarray,
    wave_1: Wave,
    wave_2: Wave,
    *,
    factor: complex,
) -> NonlinearSource:
    return NonlinearSource(
        label=label,
        k=wave_1.k + wave_2.k,
        polarization=compute_pnl_voigt(d_voigt_lab, wave_1.electric, wave_2.electric, factor=factor),
        omega=wave_1.omega + wave_2.omega,
    )


def _solve_inhomogeneous_linear_system(
    system: np.ndarray,
    rhs: np.ndarray,
    *,
    ill_conditioned: bool,
    condition_threshold: float,
    solution_policy: str,
) -> tuple[np.ndarray, str, bool]:
    if solution_policy == "solve":
        try:
            electric = np.linalg.solve(system, rhs)
            method = "solve_ill_conditioned" if ill_conditioned else "solve"
            return electric, method, ill_conditioned
        except np.linalg.LinAlgError:
            electric = _minimum_norm_solution(system, rhs, condition_threshold=condition_threshold)
            return electric, "least_squares_singular", True
    if solution_policy == "minimum_norm_if_ill_conditioned":
        if ill_conditioned:
            electric = _minimum_norm_solution(system, rhs, condition_threshold=condition_threshold)
            return electric, "minimum_norm_ill_conditioned", True
        electric = np.linalg.solve(system, rhs)
        return electric, "solve", False
    if solution_policy == "minimum_norm":
        electric = _minimum_norm_solution(system, rhs, condition_threshold=condition_threshold)
        method = "minimum_norm_ill_conditioned" if ill_conditioned else "minimum_norm"
        return electric, method, ill_conditioned
    raise ValueError("solution_policy must be 'solve', 'minimum_norm_if_ill_conditioned', or 'minimum_norm'.")


def _minimum_norm_solution(
    system: np.ndarray,
    rhs: np.ndarray,
    *,
    condition_threshold: float,
) -> np.ndarray:
    u, singular_values, vh = np.linalg.svd(system, full_matrices=False)
    if singular_values.size == 0:
        return np.zeros(system.shape[1], dtype=complex)
    cutoff = float(np.max(singular_values)) / float(condition_threshold)
    inverse = np.array(
        [1.0 / value if value > cutoff else 0.0 for value in singular_values],
        dtype=complex,
    )
    return vh.conj().T @ (inverse * (u.conj().T @ rhs))
